### ISSUE TITLE
Provide permalinks for log entries in the viewer to navigate to these directly

### ISSUE THREAD

**Issue by mbok** [logsniffer/logsniffer#51]
That feature enables users to share and bookmark links referencing a specific position in the log.
It's a low hanging fruit feature considered for quite some time, which has now become a new priority by @alibotean as mentioned in #21.

**Comment by mbok** [comment]
A link to a log entry is now available on the detail modal dialog ![Uploading permalink-log-entry.png…]()

**Comment by mbok** [comment]
Delivered within release 0.5.2

**Comment by alibotean** [comment]
Excellent news, I'm upgrading right now. Thank you.
