### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by alibotean** [logsniffer/logsniffer#54]
I would like to add a few items from my wishlist:

* grep like functionality in search: instead of going from matching log entry (line) to the next, display only lines/entries that match the search criteria. This is more like a filter instead of search
* provide a theme selector setting or widget (I'm interested in a dark theme and I'm willing to help out with it)
* do not display all the log files at once: I'm using this for 365+ days on several machines and the UI gets long quite fast since I use daily rotation

Thanks!

**Comment by mbok** [comment]
Thank you for sharing your ideas and experience! I've separated the issues into dedicates topics for a better traceability. I appreciate your interest in help out with the theme, it would be great. I would drive it via a plugin to make extensions more easier.
