### ISSUE TITLE
Search in log by severiry level

### ISSUE THREAD

**Issue by fbetil** [logsniffer/logsniffer#59]
When searching in log by "severity level scanner", dropdown show options " >= " and " = ".
So, in example, it's not possible to search for a most critical level than "WARN", because "A lower number represents critical severity and a higher number a more informative severity." (that's in the filters log configuration).
Thanks,

**Comment by mbok** [comment]
You are right! The filter defines the right order which is inspired by syslog.
The level scanner is an older component born together with the log4j reader with the wrong - reverse ordering interpretation.
I'll fix the log4j reader and add to the severity scanner all possible operands: "<", "<=" and "!=".

**Comment by mbok** [comment]
Fixed in release 0.5.3. Please download here: https://github.com/logsniffer/logsniffer/releases/tag/0.5.3

**Comment by fbetil** [comment]
That's works fine !
Thanks.
