### ISSUE TITLE
Combine file by keyword

### ISSUE THREAD

**Issue by vit1251** [logsniffer/logsniffer#67]
Hello, could I suggest to join a tens of log file in single named stream and watching all of them like it doing by shell command:

    # tail -f debug_01.log debug_02.log debug_03.log ...

I does not found this function from box. It possible now?

Thanx.

**Comment by mbok** [comment]
That's the major feature #17 of the coming release 0.6. It'll introduce a new log source type for compounding several logs into one based on timestamps. Stay tuned, it should be ready in about two weeks or so. Thus I close that issue as a duplicate.
