### ISSUE TITLE
How to check if event did not occur?

### ISSUE THREAD

**Issue by chriseverty** [logsniffer/logsniffer#75]
We have several ETL jobs that are ought to run every day. But from time to time these fail to finish. This is when we want to get a mail. So how can I define a Scanner that fires when a certain pattern is not matched since the last run?

We have a line at the end that looks like this

    2016-05-21 01:00:07,270 INFO NameOfETLProcess finished after 00:00:01 (hh:mm:ss)

If that line is missing in the log file sniffed for the current day at 8:00 we want to get a mail.

I succeeded to create the Log and the usual alerting if errors occur, but I failed to create that scanner, yet.

**Comment by mbok** [comment]
Unfortunately that isn't possible out of the box in the current version.
That use case requires a scanner with consideration of time windows, it's foreseen by the feature #45.

**Comment by chriseverty** [comment]
Closed as duplicate of #45
