### ISSUE TITLE
network syslogs

### ISSUE THREAD

**Issue by hyprvisr** [logsniffer/logsniffer#87]
Hi I have installed and configured this tool and I am pretty close.  I read another post about filters just displaying certain logs.  

For example in my case  - I want a log source that just shows all syslogs with the severity of error or higher....

Is this doable?

**Comment by mbok** [comment]
Unfortunatly it isn't possible in the viewer, here you can only use filters for searching, but not for filtering in general.

**Comment by hyprvisr** [comment]
Thanks for the quick reply
